[package]
name = "lista3"
version = "0.1.0"
edition = "2021"


[dependencies]
rand = "0.9.0-alpha.1"
env_logger = "0.11.3"
log = {version = "0.4.21", features = ["release_max_level_warn"]}
plotters = "0.3"
rand_pcg = "=0.9.0-alpha.1"
itertools = "0.12.1"